version: "3"

# SEBE Daemon Pod
#
# Runs the orchestrator alongside Proton Bridge and signal-cli.
# LLM inference stays on bare metal (llama-server needs GPU access).
#
# Usage:
#   podman-compose up -d
#   podman-compose logs -f sebe-orchestrator
#   podman-compose down
#
# Prerequisites:
#   - Copy .env.template to .env and fill in credentials
#   - Proton Bridge: first run requires interactive login (see README)
#   - signal-cli: first run requires device linking (see README)

services:

  # --- Proton Mail Bridge ---
  # Exposes IMAP (1143) and SMTP (1025) for email access.
  # Persistent volume stores auth state so you only log in once.
  proton-bridge:
    image: docker.io/shenxn/protonmail-bridge:latest
    container_name: sebe-proton-bridge
    restart: unless-stopped
    volumes:
      - proton-bridge-data:/root/.config/protonmail/bridge-v3
    ports:
      - "1143:1143"   # IMAP
      - "1025:1025"   # SMTP
    environment:
      - PROTON_BRIDGE_NONINTERACTIVE=1

  # --- signal-cli REST API ---
  # Exposes a REST API for sending/receiving Signal messages.
  # Persistent volume stores Signal account keys and session.
  signal-cli:
    image: docker.io/bbernhard/signal-cli-rest-api:latest
    container_name: sebe-signal-cli
    restart: unless-stopped
    volumes:
      - signal-cli-data:/home/.local/share/signal-cli
    ports:
      - "8082:8080"   # REST API (remapped to avoid clash with llama-server)
    environment:
      - MODE=json-rpc

  # --- SEBE Orchestrator ---
  # The daemon that polls channels and routes to LLMs.
  sebe-orchestrator:
    build:
      context: .
      dockerfile: Containerfile
    container_name: sebe-orchestrator
    restart: unless-stopped
    depends_on:
      - proton-bridge
      - signal-cli
    env_file:
      - ../../.env
    environment:
      # Override defaults for container networking.
      # Proton Bridge is accessible via the service name within the pod,
      # or via host ports if using host network mode.
      - PROTON_IMAP_HOST=proton-bridge
      - PROTON_SMTP_HOST=proton-bridge
      # signal-cli REST API
      - SIGNAL_API_URL=http://signal-cli:8080
      # LLM endpoint (bare metal on the host).
      # host.containers.internal resolves to the host from within Podman.
      - LLM_BASE_URL=http://host.containers.internal:8080/v1
    volumes:
      # Mount the memory DB so the orchestrator can log interactions
      - ../../automation_framework/data:/app/data:z
      - ../../automation_framework/memory:/app/memory:z

volumes:
  proton-bridge-data:
  signal-cli-data:
